import { SpaceSummary } from "./types";

export const demoSpaces:SpaceSummary[]=[
  {id:"s1",title:"Orchid Metro Deck",zone:"Indiranagar",mode:"PARKING",price:80,distanceKm:.3,available:12,capacity:18,reliability:96,freshness:"LIVE",forecast:9,verified:true,verificationStatus:"APPROVED",operationalStatus:"ACTIVE",covered:true,monthlyPrice:6400,coordinates:{lat:12.978,lng:77.640},owner:"Orchid Mobility",amenities:["Covered","CCTV","Two-wheeler bays"],vehicleTypes:["CAR"]},
  {id:"s2",title:"12th Main EV Hub",zone:"Indiranagar",mode:"EV",price:110,distanceKm:.7,available:4,capacity:10,reliability:93,freshness:"RECENT",forecast:3,verified:true,verificationStatus:"APPROVED",operationalStatus:"ACTIVE",ev:true,covered:true,connector:"CCS2",coordinates:{lat:12.974,lng:77.645},owner:"Volt City",amenities:["22kW charging","CCS2 connector","₹12/kWh charging"],vehicleTypes:["CAR"]},
  {id:"s3",title:"Civic Loading Bay",zone:"Koramangala",mode:"LOADING",price:120,distanceKm:1.2,available:3,capacity:4,reliability:91,freshness:"LIVE",forecast:2,verified:true,verificationStatus:"APPROVED",operationalStatus:"ACTIVE",maxDwellMinutes:30,vehicleTypes:["VAN","LCV"],coordinates:{lat:12.935,lng:77.624},owner:"Civic Operations",amenities:["LCV / Van","30 min dwell","10:00–12:00 delivery window"]},
  {id:"s4",title:"Metro Access Plaza",zone:"Indiranagar",mode:"ACCESSIBILITY",price:60,distanceKm:.5,available:2,capacity:3,reliability:98,freshness:"LIVE",forecast:1,verified:true,verificationStatus:"APPROVED",operationalStatus:"ACTIVE",accessible:true,coordinates:{lat:12.971,lng:77.638},owner:"Metro Access",amenities:["Step-free","Attendant"],vehicleTypes:["CAR"]},
  {id:"s5",title:"Brigade Pickup Loop",zone:"MG Road",mode:"PICKUP",price:45,distanceKm:1.5,available:6,capacity:8,reliability:88,freshness:"RECENT",forecast:4,verified:true,verificationStatus:"APPROVED",operationalStatus:"ACTIVE",maxDwellMinutes:10,vehicleTypes:["CAR"],coordinates:{lat:12.974,lng:77.610},owner:"Brigade Loop",amenities:["10 min window"]},
  {id:"s6",title:"Pending Garden Space",zone:"Ulsoor",mode:"PARKING",price:55,distanceKm:2.1,available:2,capacity:8,reliability:72,freshness:"STALE",forecast:4,verified:false,verificationStatus:"PENDING",operationalStatus:"INACTIVE",coordinates:{lat:12.981,lng:77.625},owner:"Garden Parking",amenities:[],vehicleTypes:["CAR"]},
  {id:"s7",title:"Richmond Avenue Garage",zone:"Richmond Town",mode:"PARKING",price:80,distanceKm:1.1,available:1,capacity:20,reliability:91,freshness:"LIVE",forecast:0,verified:true,verificationStatus:"APPROVED",operationalStatus:"ACTIVE",covered:false,monthlyPrice:5200,coordinates:{lat:12.966,lng:77.604},owner:"Avenue Garage",amenities:["CCTV","Security"],vehicleTypes:["CAR"]},
  {id:"s8",title:"Forum Overflow Lot",zone:"Koramangala",mode:"PARKING",price:70,distanceKm:1.8,available:0,capacity:24,reliability:86,freshness:"RECENT",forecast:2,verified:true,verificationStatus:"APPROVED",operationalStatus:"ACTIVE",coordinates:{lat:12.934,lng:77.611},owner:"Forum Ops",amenities:["Open-air"],vehicleTypes:["CAR"]},
];

