import { SpaceSummary } from "@/lib/types";
export type Freshness="LIVE"|"RECENT"|"STALE";export type Severity="NORMAL"|"WATCH"|"HIGH_DEMAND"|"SHORTAGE_RISK"|"SHORTAGE";
export const intelligenceConfig={liveSeconds:60,recentSeconds:600,shortageRatio:.12,watchRatio:.3};
export function freshness(updatedAt:Date,now=new Date()):Freshness{const age=(now.getTime()-updatedAt.getTime())/1000;return age<=intelligenceConfig.liveSeconds?"LIVE":age<=intelligenceConfig.recentSeconds?"RECENT":"STALE"}
export function availabilityConfidence(input:{freshness:Freshness;source:"MANUAL"|"SIMULATED_SENSOR"|"BOOKING_DERIVED";ownerReliability:number;accuracy:number}){const f={LIVE:40,RECENT:27,STALE:10}[input.freshness];const source={MANUAL:8,SIMULATED_SENSOR:16,BOOKING_DERIVED:12}[input.source];const score=Math.round(f+source+input.ownerReliability*.2+input.accuracy*.2);return {score,level:score>=75?"HIGH":score>=50?"MEDIUM":"LOW"} as const}
export function forecastAvailability(input:{available:number;capacity:number;hour:number;recentTrend:number;eventMultiplier?:number}){const peak=input.hour>=18&&input.hour<=20?.24:input.hour>=10&&input.hour<=13?.14:.04;const demand=Math.round(input.capacity*(peak+(input.eventMultiplier ?? 0)+Math.max(0,input.recentTrend)));const forecast=Math.max(0,input.available-demand);return {demand,available:forecast,confidence:input.recentTrend>.25?"MEDIUM":"HIGH" as "HIGH"|"MEDIUM"}}
export function shortageSeverity(available:number,capacity:number):Severity{const r=available/Math.max(1,capacity);return r===0?"SHORTAGE":r<=intelligenceConfig.shortageRatio?"SHORTAGE_RISK":r<=intelligenceConfig.watchRatio?"HIGH_DEMAND":r<=.5?"WATCH":"NORMAL"}
export function utilization(capacity:number,available:number){return Math.round((1-available/Math.max(1,capacity))*100)}
export function underutilized(capacity:number,available:number){return utilization(capacity,available)<35}
export function detectAnomalies(events:{available:number;at:Date}[]){return events.slice(1).flatMap((e,i)=>Math.abs(e.available-events[i].available)>=5?[{type:"AVAILABILITY_SWING",at:e.at}]:[])}
export function priceRecommendation(price:number,utilizationPercent:number,severity:Severity){if(["SHORTAGE","SHORTAGE_RISK"].includes(severity)&&utilizationPercent>=85)return {recommended:Math.round(price*1.12),reason:"Projected shortage during the selected peak window."};return {recommended:price,reason:"Keep current price; demand does not justify a change."}}
export function intelligenceRecommendation(spaces:SpaceSummary[],arrivalHour:number){return spaces.filter(s=>s.verified&&s.available>0).map(s=>{const fc=forecastAvailability({available:s.available,capacity:s.capacity??10,hour:arrivalHour,recentTrend:Math.max(0,(s.available-s.forecast)/Math.max(1,s.capacity??10))});const confidence=availabilityConfidence({freshness:s.freshness,source:"BOOKING_DERIVED",ownerReliability:s.reliability,accuracy:s.reliability});const score=s.reliability*.35+fc.available*4+confidence.score*.25-s.distanceKm*5-s.price*.03;return {...s,score,forecast:fc,confidence,reason:`Verified · ${confidence.level.toLowerCase()} availability confidence · ${fc.available} expected free at your time`}}).sort((a,b)=>b.score-a.score)}


